### ISSUE TITLE
require for the code of NW-UCLA data processing

### ISSUE THREAD

**Issue by yanghhx** [Boeun-Kim/GL-Transformer#2]
I am quite interested in your work. Could you please offer me the code of NW-UCLA data processing for unsupervised learning?

**Comment by Boeun-Kim** [comment]
Thank you for your interest in my research. I used the preprocessed NW-UCLA data by Predict&Cluster which can be downloaded from the link below. 
https://github.com/shlizee/Predict-Cluster/tree/master/ucla_github_pytorch/UCLAdata

**Comment by yanghhx** [comment]
Thanks for your help.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 11/19/2022 15:50 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [Boeun-Kim/GL-Transformer] require for the code of NW-UCLA data processing (Issue #2) |

Thank you for your interest in my research. I used the preprocessed NW-UCLA data by Predict&Cluster which can be downloaded from the link below.
https://github.com/shlizee/Predict-Cluster/tree/master/ucla_github_pytorch/UCLAdata
