### ISSUE TITLE
Pretraining weights unavailable

### ISSUE THREAD

**Issue by chinjouli** [Boeun-Kim/GL-Transformer#3]
Hi, I'm interested in reproducing your work.
I found that the links to pretraining weights (in README.md) are not working now. Is there any possibility that the links can be updated?

**Comment by Boeun-Kim** [comment]
Thank you for your interest.
I have provided new links for the pretrained weights.

**Comment by JiaweiMorris** [comment]
> Thank you for your interest. I have provided new links for the pretrained weights.

According to the model file name, are the links in the wrong order?

**Comment by Boeun-Kim** [comment]
You are right. Thank you for letting me know 👍
