### ISSUE TITLE
Train on custom video dataset

### ISSUE THREAD

**Issue by CSLR-research** [Boeun-Kim/GL-Transformer#4]
Thank you for your amazing work. 
I want to train the model on another video-based dataset, using off-shelf pose estimators like mediapipe or mmpose to extract pose keypoints. I wondering if I can use the extracted keypoints (xyz coordinates) directly or is some prepossessing necessary? I'm not sure what is the neighbor_1base and parallel_skeleton used for in the NTUMotionProcessor. 

Thanks again!

**Comment by Boeun-Kim** [comment]
Thanks for the question. If you use a different skeleton format, you need to implement the code for preprocessing and data feeding.

neighbor_1base: Information about the skeleton tree. Each bone has a parent and a child, and neighbor_1base represents the relationship.

parallel_skeleton: This is used for preprocessing. We rotate each skeleton data to align in the same direction.
